//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerRequestMsg : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlannerRequest";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public float start_x;
        public float start_y;
        public float start_z;
        public float end_x;
        public float end_y;
        public float end_z;

        public PathPlannerRequestMsg()
        {
            this.robot_id = 0;
            this.start_x = 0.0f;
            this.start_y = 0.0f;
            this.start_z = 0.0f;
            this.end_x = 0.0f;
            this.end_y = 0.0f;
            this.end_z = 0.0f;
        }

        public PathPlannerRequestMsg(int robot_id, float start_x, float start_y, float start_z, float end_x, float end_y, float end_z)
        {
            this.robot_id = robot_id;
            this.start_x = start_x;
            this.start_y = start_y;
            this.start_z = start_z;
            this.end_x = end_x;
            this.end_y = end_y;
            this.end_z = end_z;
        }

        public static PathPlannerRequestMsg Deserialize(MessageDeserializer deserializer) => new PathPlannerRequestMsg(deserializer);

        private PathPlannerRequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.start_x);
            deserializer.Read(out this.start_y);
            deserializer.Read(out this.start_z);
            deserializer.Read(out this.end_x);
            deserializer.Read(out this.end_y);
            deserializer.Read(out this.end_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.start_x);
            serializer.Write(this.start_y);
            serializer.Write(this.start_z);
            serializer.Write(this.end_x);
            serializer.Write(this.end_y);
            serializer.Write(this.end_z);
        }

        public override string ToString()
        {
            return "PathPlannerRequestMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\nstart_x: " + start_x.ToString() +
            "\nstart_y: " + start_y.ToString() +
            "\nstart_z: " + start_z.ToString() +
            "\nend_x: " + end_x.ToString() +
            "\nend_y: " + end_y.ToString() +
            "\nend_z: " + end_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
