//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerBatteryRequestMsg : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlannerBatteryRequest";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public float start_x;
        public float start_y;

        public PathPlannerBatteryRequestMsg()
        {
            this.robot_id = 0;
            this.start_x = 0.0f;
            this.start_y = 0.0f;
        }

        public PathPlannerBatteryRequestMsg(int robot_id, float start_x, float start_y)
        {
            this.robot_id = robot_id;
            this.start_x = start_x;
            this.start_y = start_y;
        }

        public static PathPlannerBatteryRequestMsg Deserialize(MessageDeserializer deserializer) => new PathPlannerBatteryRequestMsg(deserializer);

        private PathPlannerBatteryRequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.start_x);
            deserializer.Read(out this.start_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.start_x);
            serializer.Write(this.start_y);
        }

        public override string ToString()
        {
            return "PathPlannerBatteryRequestMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\nstart_x: " + start_x.ToString() +
            "\nstart_y: " + start_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
