//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ObstacleManager
{
    [Serializable]
    public class ObstacleManagerReportMsg : Message
    {
        public const string k_RosMessageName = "obstacle_manager/ObstacleManagerReport";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float z;
        public string type;
        public string status;
        public float scale_x;
        public float scale_y;
        public float scale_z;
        public string id;

        public ObstacleManagerReportMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.type = "";
            this.status = "";
            this.scale_x = 0.0f;
            this.scale_y = 0.0f;
            this.scale_z = 0.0f;
            this.id = "";
        }

        public ObstacleManagerReportMsg(float x, float y, float z, string type, string status, float scale_x, float scale_y, float scale_z, string id)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.type = type;
            this.status = status;
            this.scale_x = scale_x;
            this.scale_y = scale_y;
            this.scale_z = scale_z;
            this.id = id;
        }

        public static ObstacleManagerReportMsg Deserialize(MessageDeserializer deserializer) => new ObstacleManagerReportMsg(deserializer);

        private ObstacleManagerReportMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.type);
            deserializer.Read(out this.status);
            deserializer.Read(out this.scale_x);
            deserializer.Read(out this.scale_y);
            deserializer.Read(out this.scale_z);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.type);
            serializer.Write(this.status);
            serializer.Write(this.scale_x);
            serializer.Write(this.scale_y);
            serializer.Write(this.scale_z);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "ObstacleManagerReportMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\ntype: " + type.ToString() +
            "\nstatus: " + status.ToString() +
            "\nscale_x: " + scale_x.ToString() +
            "\nscale_y: " + scale_y.ToString() +
            "\nscale_z: " + scale_z.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
