//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RobotManager
{
    [Serializable]
    public class RobotManagerBatteryMsgMsg : Message
    {
        public const string k_RosMessageName = "robot_manager/RobotManagerBatteryMsg";
        public override string RosMessageName => k_RosMessageName;

        public float[] x;
        public float[] y;

        public RobotManagerBatteryMsgMsg()
        {
            this.x = new float[0];
            this.y = new float[0];
        }

        public RobotManagerBatteryMsgMsg(float[] x, float[] y)
        {
            this.x = x;
            this.y = y;
        }

        public static RobotManagerBatteryMsgMsg Deserialize(MessageDeserializer deserializer) => new RobotManagerBatteryMsgMsg(deserializer);

        private RobotManagerBatteryMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.y, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.x);
            serializer.Write(this.x);
            serializer.WriteLength(this.y);
            serializer.Write(this.y);
        }

        public override string ToString()
        {
            return "RobotManagerBatteryMsgMsg: " +
            "\nx: " + System.String.Join(", ", x.ToList()) +
            "\ny: " + System.String.Join(", ", y.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
