//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RobotManager
{
    [Serializable]
    public class RobotManagerTrackerMsg : Message
    {
        public const string k_RosMessageName = "robot_manager/RobotManagerTracker";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public float current_x;
        public float current_y;
        public float current_z;
        public float start_x;
        public float start_y;
        public float start_z;
        public float end_x;
        public float end_y;
        public float end_z;
        public float move_speed;
        public bool loop;
        public float[] destinations_x;
        public float[] destinations_y;
        public float[] destinations_z;
        public bool obstacle_detected;
        public bool performing_task;
        public float perception_radius;
        public float obstacle_distance_threshold;
        public string robot_type;

        public RobotManagerTrackerMsg()
        {
            this.robot_id = 0;
            this.current_x = 0.0f;
            this.current_y = 0.0f;
            this.current_z = 0.0f;
            this.start_x = 0.0f;
            this.start_y = 0.0f;
            this.start_z = 0.0f;
            this.end_x = 0.0f;
            this.end_y = 0.0f;
            this.end_z = 0.0f;
            this.move_speed = 0.0f;
            this.loop = false;
            this.destinations_x = new float[0];
            this.destinations_y = new float[0];
            this.destinations_z = new float[0];
            this.obstacle_detected = false;
            this.performing_task = false;
            this.perception_radius = 0.0f;
            this.obstacle_distance_threshold = 0.0f;
            this.robot_type = "";
        }

        public RobotManagerTrackerMsg(int robot_id, float current_x, float current_y, float current_z, float start_x, float start_y, float start_z, float end_x, float end_y, float end_z, float move_speed, bool loop, float[] destinations_x, float[] destinations_y, float[] destinations_z, bool obstacle_detected, bool performing_task, float perception_radius, float obstacle_distance_threshold, string robot_type)
        {
            this.robot_id = robot_id;
            this.current_x = current_x;
            this.current_y = current_y;
            this.current_z = current_z;
            this.start_x = start_x;
            this.start_y = start_y;
            this.start_z = start_z;
            this.end_x = end_x;
            this.end_y = end_y;
            this.end_z = end_z;
            this.move_speed = move_speed;
            this.loop = loop;
            this.destinations_x = destinations_x;
            this.destinations_y = destinations_y;
            this.destinations_z = destinations_z;
            this.obstacle_detected = obstacle_detected;
            this.performing_task = performing_task;
            this.perception_radius = perception_radius;
            this.obstacle_distance_threshold = obstacle_distance_threshold;
            this.robot_type = robot_type;
        }

        public static RobotManagerTrackerMsg Deserialize(MessageDeserializer deserializer) => new RobotManagerTrackerMsg(deserializer);

        private RobotManagerTrackerMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.current_x);
            deserializer.Read(out this.current_y);
            deserializer.Read(out this.current_z);
            deserializer.Read(out this.start_x);
            deserializer.Read(out this.start_y);
            deserializer.Read(out this.start_z);
            deserializer.Read(out this.end_x);
            deserializer.Read(out this.end_y);
            deserializer.Read(out this.end_z);
            deserializer.Read(out this.move_speed);
            deserializer.Read(out this.loop);
            deserializer.Read(out this.destinations_x, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.destinations_y, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.destinations_z, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.obstacle_detected);
            deserializer.Read(out this.performing_task);
            deserializer.Read(out this.perception_radius);
            deserializer.Read(out this.obstacle_distance_threshold);
            deserializer.Read(out this.robot_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.current_x);
            serializer.Write(this.current_y);
            serializer.Write(this.current_z);
            serializer.Write(this.start_x);
            serializer.Write(this.start_y);
            serializer.Write(this.start_z);
            serializer.Write(this.end_x);
            serializer.Write(this.end_y);
            serializer.Write(this.end_z);
            serializer.Write(this.move_speed);
            serializer.Write(this.loop);
            serializer.WriteLength(this.destinations_x);
            serializer.Write(this.destinations_x);
            serializer.WriteLength(this.destinations_y);
            serializer.Write(this.destinations_y);
            serializer.WriteLength(this.destinations_z);
            serializer.Write(this.destinations_z);
            serializer.Write(this.obstacle_detected);
            serializer.Write(this.performing_task);
            serializer.Write(this.perception_radius);
            serializer.Write(this.obstacle_distance_threshold);
            serializer.Write(this.robot_type);
        }

        public override string ToString()
        {
            return "RobotManagerTrackerMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\ncurrent_x: " + current_x.ToString() +
            "\ncurrent_y: " + current_y.ToString() +
            "\ncurrent_z: " + current_z.ToString() +
            "\nstart_x: " + start_x.ToString() +
            "\nstart_y: " + start_y.ToString() +
            "\nstart_z: " + start_z.ToString() +
            "\nend_x: " + end_x.ToString() +
            "\nend_y: " + end_y.ToString() +
            "\nend_z: " + end_z.ToString() +
            "\nmove_speed: " + move_speed.ToString() +
            "\nloop: " + loop.ToString() +
            "\ndestinations_x: " + System.String.Join(", ", destinations_x.ToList()) +
            "\ndestinations_y: " + System.String.Join(", ", destinations_y.ToList()) +
            "\ndestinations_z: " + System.String.Join(", ", destinations_z.ToList()) +
            "\nobstacle_detected: " + obstacle_detected.ToString() +
            "\nperforming_task: " + performing_task.ToString() +
            "\nperception_radius: " + perception_radius.ToString() +
            "\nobstacle_distance_threshold: " + obstacle_distance_threshold.ToString() +
            "\nrobot_type: " + robot_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
